global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Bangla Backend API
  - job_name: 'bangla-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (if you add postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:9187']

  # Redis metrics (if you add redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis:9121']

  # Node Exporter (system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
